"use client";

import { FormEvent, useState } from "react";
import type { KandenLookup, TossFormInput } from "../_lib/form";
import styles from "./page.module.css";

const initial: TossFormInput = { email:"",useTossCb:"利用しない",tossCbAmount:"",tossUpItems:[],comment:"",rank:"C",preferredTimes:[],listCategory:"リスト内",pdManagementNumber:"",pd:"",applicantType:"本人",applicantLastName:"",applicantFirstName:"",applicantLastKana:"",applicantFirstKana:"",birthDate:"",addressType:"現住所",postalCode:"",prefecture:"",city:"",town:"",building:"",room:"",contactType:"本人",contactPhone:"",smartphoneCarrier:"その他" };
const selects = { useTossCb:["利用する","利用しない"],rank:["S","A","B","C","D"],listCategory:["リスト内","リスト外"],applicantType:["本人","家族","法人"],addressType:["現住所","転居先","その他"],contactType:["本人","家族","その他"],smartphoneCarrier:["docomo","au","SoftBank","楽天モバイル","その他"] } as const;
// PD（app63のPD項目・接頭辞付き）はPD管理番号から自動生成する（二重入力させない）。
const toPd=(managementNumber:string)=>managementNumber.trim()?`PD${managementNumber.trim()}`:"";
// 照合結果の項目名を日本語で表示する。
const LOOKUP_LABELS:Record<string,string>={listName:"リスト名",customerNumber:"お客様番号",phone:"電話番号",contractNameKanji:"契約名義(漢字)",contractNameKana:"契約名義(カナ)",postalCode:"郵便番号",address1:"住所1",address2:"住所2",leavingDestination:"離脱先",leavingDate:"離脱時期",contractType:"契約種別",contractCapacityLight:"契約容量(従量)",contractCapacityPower:"契約容量(動力)",kandenGasContract:"関電ガス契約",powerContract:"動力契約",demandStartDate:"需要開始日",annualUsageLight:"年間使用量(電灯)",monthlyUsageLight:"月間使用量(電灯)",monthlyUsagePower:"月間使用量(動力)"};
const fields: {key:keyof TossFormInput;label:string;required?:boolean;type?:string}[] = [
  {key:"email",label:"メールアドレス",required:true,type:"email"},{key:"tossCbAmount",label:"トスCB金額",type:"number"},{key:"pdManagementNumber",label:"PD管理番号",required:true},
  {key:"applicantLastName",label:"申込者 姓",required:true},{key:"applicantFirstName",label:"申込者 名",required:true},{key:"applicantLastKana",label:"申込者 セイ",required:true},{key:"applicantFirstKana",label:"申込者 メイ",required:true},{key:"birthDate",label:"生年月日",required:true,type:"date"},
  {key:"postalCode",label:"郵便番号",required:true},{key:"prefecture",label:"都道府県",required:true},{key:"city",label:"市区町村",required:true},{key:"town",label:"町域・番地",required:true},{key:"building",label:"建物名"},{key:"room",label:"部屋番号"},{key:"contactPhone",label:"連絡先電話番号",required:true,type:"tel"},
];

export default function TossForm() {
  const [form,setForm]=useState(initial); const [lookup,setLookup]=useState<KandenLookup|null>(null); const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false);
  const set=(key:keyof TossFormInput,value:string|string[])=>setForm(current=>({...current,[key]:value}));
  const multi=(key:"tossUpItems"|"preferredTimes",value:string,checked:boolean)=>set(key,checked?[...form[key],value]:form[key].filter(x=>x!==value));
  async function lookupPd(){if(!form.pdManagementNumber.trim()){setMessage("PD管理番号を入力してください。");return;}setBusy(true);setMessage("関電リストを照合しています…");try{const r=await fetch(`/api/toss/kanden-lookup?pd=${encodeURIComponent(form.pdManagementNumber)}`);const b=await r.json();if(!r.ok)throw new Error(b.error);if(!b.found){setLookup(null);set("listCategory","リスト外");setMessage("一致するリストがありません。手入力してください。");return;}setLookup(b.data);setForm(c=>({...c,listCategory:"リスト内",postalCode:b.data.postalCode.replace(/-/g,""),contactPhone:b.data.phone}));setMessage("関電リストと一致しました。");}catch(e){setMessage(e instanceof Error?e.message:"照合に失敗しました");}finally{setBusy(false);}}
  async function lookupPostal(){setBusy(true);try{const r=await fetch(`/api/toss/postal?zip=${encodeURIComponent(form.postalCode)}`);const b=await r.json();if(!r.ok)throw new Error(b.error);if(!b.found)throw new Error("住所が見つかりませんでした");setForm(c=>({...c,...b.data}));setMessage("住所を補完しました。");}catch(e){setMessage(e instanceof Error?e.message:"住所検索に失敗しました");}finally{setBusy(false);}}
  async function submit(e:FormEvent){e.preventDefault();setBusy(true);setMessage("送信しています…");try{const r=await fetch("/api/toss/submit",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const b=await r.json();if(!r.ok)throw new Error(b.error);setMessage(`登録完了（レコード番号: ${b.recordId}）`);setForm(initial);setLookup(null);scrollTo({top:0,behavior:"smooth"});}catch(error){setMessage(error instanceof Error?error.message:"送信に失敗しました");}finally{setBusy(false);}}
  const onField=(key:keyof TossFormInput,value:string)=>key==="pdManagementNumber"?setForm(c=>({...c,pdManagementNumber:value,pd:toPd(value)})):set(key,value);
  const text=(from:number,to?:number)=>fields.slice(from,to).map(f=><label key={f.key}>{f.label}{f.required&&<em>必須</em>}<input type={f.type||"text"} value={String(form[f.key])} required={f.required} onChange={e=>onField(f.key,e.target.value)}/></label>);
  return <form className={styles.form} onSubmit={submit}>{message&&<div className={styles.notice} role="status">{message}</div>}
    <section><h2>トス情報</h2><div className={styles.grid}><Select label="トスCB有無" value={form.useTossCb} options={selects.useTossCb} change={v=>set("useTossCb",v)}/><Select label="トスランク" value={form.rank} options={selects.rank} change={v=>set("rank",v)}/><Select label="関電リスト区分" value={form.listCategory} options={selects.listCategory} change={v=>set("listCategory",v)}/>{text(0,3)}<Checks label="トスアップ項目" values={form.tossUpItems} options={["電気","ガス","通信","その他"]} change={(v,c)=>multi("tossUpItems",v,c)}/><Checks label="連絡希望時間帯" values={form.preferredTimes} options={["午前","12〜15時","15〜18時","18時以降"]} change={(v,c)=>multi("preferredTimes",v,c)}/><label className={styles.wide}>トス者コメント<textarea rows={4} value={form.comment} onChange={e=>set("comment",e.target.value)}/></label></div></section>
    <section><h2>関電リスト照合</h2><button type="button" disabled={busy} onClick={lookupPd}>PD管理番号で照合</button>{lookup&&<dl className={styles.result}>{Object.entries(lookup).map(([k,v])=><div key={k}><dt>{LOOKUP_LABELS[k]??k}</dt><dd>{v||"—"}</dd></div>)}</dl>}</section>
    <section><h2>申込者情報</h2><div className={styles.grid}><Select label="申込者区分" value={form.applicantType} options={selects.applicantType} change={v=>set("applicantType",v)}/>{text(3,9)}</div></section>
    <section><h2>住所・連絡先</h2><div className={styles.grid}><Select label="住所区分" value={form.addressType} options={selects.addressType} change={v=>set("addressType",v)}/>{text(9,10)}<button type="button" disabled={busy} onClick={lookupPostal}>住所を検索</button>{text(10)}<Select label="連絡先区分" value={form.contactType} options={selects.contactType} change={v=>set("contactType",v)}/><Select label="スマホキャリア" value={form.smartphoneCarrier} options={selects.smartphoneCarrier} change={v=>set("smartphoneCarrier",v)}/></div></section>
    <button className={styles.submit} disabled={busy}>{busy?"処理中…":"内容を送信する"}</button></form>;
}
function Select({label,value,options,change}:{label:string;value:string;options:readonly string[];change:(v:string)=>void}){return <label>{label}<select value={value} onChange={e=>change(e.target.value)}>{options.map(x=><option key={x}>{x}</option>)}</select></label>}
function Checks({label,values,options,change}:{label:string;values:string[];options:string[];change:(v:string,c:boolean)=>void}){return <fieldset className={styles.wide}><legend>{label}</legend>{options.map(x=><label key={x}><input type="checkbox" checked={values.includes(x)} onChange={e=>change(x,e.target.checked)}/>{x}</label>)}</fieldset>}
