// 将来 Root（組織マスタ）にデータを集約し、ミラー取得に差し替える前提。現在はデモのため静的データ。
// 差し替え時は、このファイルの取得元のみ変更し、BlueprintDashboard 側にデータをベタ書きしない。
export type ModuleBlueprint = {
  id: string;
  name: string;
  code2: string;
  role: string;
  summary: string;
  features: string[];
  relations: string;
  folder: string;
  stageLabel: string;
  iconSrc: string;
  note?: string;
};

export const blueprintCommonNotes = [
  "全モジュール共通: FileMaker 風 UX（Ctrl+F 検索・演算子・ショートカット）に準拠。",
  "案件 ID: G + モジュール2文字コード + 7桁連番（例 GBU0000001）。Soil のみ GSO-YYYYMMDD-NNNNNN。",
  "全モジュールは Root（組織マスタ）の正本データを参照する。",
] as const;

export const moduleBlueprints: ModuleBlueprint[] = [
  {
    id: "bloom",
    name: "Bloom",
    code2: "BL",
    role: "案件KPI（中心ダッシュボード）",
    stageLabel: "開発中",
    summary: "各モジュールの状況を集約し、経営・現場が一目で把握できる中心庭園。",
    features: ["設計図", "開発進捗", "経営状況", "ワークボード", "日報", "月次まとめ", "統合KPI"],
    relations: "Root・Forest・Tree・Bud などのデータを集約表示",
    folder: "080_Bloom_案件KPI",
    iconSrc: "/themes/garden-shell/images/icons_bloom/orb_bloom.png",
  },
  {
    id: "fruit",
    name: "Fruit",
    code2: "FR",
    role: "法人実態情報",
    stageLabel: "構想",
    summary: "法人ごとの基本情報・証跡・関係性を束ねる実りの台帳。",
    features: ["法人プロフィール", "証跡・関係性の台帳（構想段階）"],
    relations: "Root（法人マスタ）・Forest（決算）",
    folder: "120_Fruit_法人実態情報",
    iconSrc: "/themes/garden-shell/images/icons_bloom/orb_fruit.png",
  },
  {
    id: "seed",
    name: "Seed",
    code2: "SE",
    role: "新規事業",
    stageLabel: "構想",
    summary: "新規事業・新商材の構想を育てる初期検討の畑。",
    features: ["事業アイデア管理", "初期検討メモ（構想段階）"],
    relations: "-",
    folder: "090_Seed_新規事業",
    iconSrc: "/themes/garden-shell/images/icons_bloom/orb_seed.png",
  },
  {
    id: "forest",
    name: "Forest",
    code2: "FO",
    role: "全法人決算",
    stageLabel: "開発中",
    summary: "全法人の決算・会計・経営ダッシュボードを束ねる森。",
    features: ["経営ダッシュボード（v1 公開済）", "月次売上・決算"],
    relations: "Bud（経理）・Root（法人マスタ）からデータ集約",
    folder: "100_Forest_全法人決算",
    iconSrc: "/themes/garden-shell/images/icons_bloom/orb_forest.png",
  },
  {
    id: "bud",
    name: "Bud",
    code2: "BU",
    role: "経理収支",
    stageLabel: "開発中",
    summary: "収支・仕訳・振込・請求書管理を支えるつぼみ。",
    features: ["仕訳", "振込管理", "請求書管理", "給与処理・給与チェック自動化", "法人別経理", "マネーフォワード連携"],
    relations: "Root（マスタ）・Forest（決算）へ連携",
    folder: "070_Bud_経理収支",
    iconSrc: "/themes/garden-shell/images/icons_bloom/orb_bud.png",
  },
  {
    id: "leaf",
    name: "Leaf",
    code2: "LE",
    role: "個別業務アプリ",
    stageLabel: "開発中",
    summary: "関連会社・部門ごとの個別業務アプリを伸ばす葉。",
    features: ["関電（Kanden）業務委託＝案件ステータス・業務フロー・撮影画像保管・Backoffice 検索"],
    relations: "Root（マスタ）・Tree（架電）",
    folder: "060_Leaf_個別アプリ",
    iconSrc: "/themes/garden-shell/images/icons_bloom/orb_leaf.png",
  },
  {
    id: "tree",
    name: "Tree",
    code2: "TR",
    role: "架電",
    stageLabel: "公開済",
    summary: "確認・営業現場・架電オペレーションを支える幹。",
    features: ["架電アプリ（初版リリース済）", "通話履歴", "架電システム内製化"],
    relations: "Root（顧客マスタ）・Leaf",
    folder: "050_Tree_架電",
    iconSrc: "/themes/garden-shell/images/icons_bloom/orb_tree.png",
  },
  {
    id: "sprout",
    name: "Sprout",
    code2: "（未割当）",
    role: "採用",
    stageLabel: "構想",
    summary: "応募・面接・内定・入社準備までを整える芽。",
    features: ["応募管理", "面接・内定", "入社準備（構想段階）"],
    relations: "Root（従業員マスタ）・Calendar（面接枠）",
    folder: "130_Sprout_採用",
    iconSrc: "/themes/garden-shell/images/icons_bloom/orb_sprout.png",
  },
  {
    id: "soil",
    name: "Soil",
    code2: "SO",
    role: "DB基盤",
    stageLabel: "構想",
    summary: "大量データ・インポート・基盤データの土壌。",
    features: ["大量データインポート", "基盤データ管理（構想段階）"],
    relations: "全モジュールの基盤",
    folder: "030_Soil_DB基盤",
    iconSrc: "/themes/garden-shell/images/icons_bloom/orb_soil.png",
    note: "ID 体系が別（GSO-YYYYMMDD-NNNNNN）、純粋な大量データは UUID/bigint",
  },
  {
    id: "root",
    name: "Root",
    code2: "RO",
    role: "組織マスタ",
    stageLabel: "公開済",
    summary: "従業員・顧客・権限・組織マスタの正本を支える根。全モジュールが参照する中心。",
    features: ["従業員/顧客/会社マスタ", "7 段階権限", "法人マスタ統合（Forest 連携）", "マネーフォワード電子契約連携"],
    relations: "全モジュール（マスタ供給元）",
    folder: "040_Root_組織マスタ",
    iconSrc: "/themes/garden-shell/images/icons_bloom/orb_root.png",
    note: "将来は設計図など各モジュールのデータもここに集約する構想",
  },
  {
    id: "rill",
    name: "Rill",
    code2: "RI",
    role: "メッセージ",
    stageLabel: "開発中",
    summary: "社内連絡・通知・メッセージング連携を流す小川。",
    features: ["社内連絡", "通知", "メッセージング連携"],
    relations: "Root（従業員マスタ）",
    folder: "110_Rill_メッセージ",
    iconSrc: "/themes/garden-shell/images/icons_bloom/orb_rill.png",
    note: "チャット特化 UI（FileMaker 風 UX から逸脱可）",
  },
  {
    id: "calendar",
    name: "Calendar",
    code2: "（未割当）",
    role: "予定管理",
    stageLabel: "構想",
    summary: "営業予定・面接枠・シフトを横断管理する暦。",
    features: ["営業予定", "面接枠", "シフト横断管理（構想段階）"],
    relations: "Tree（営業）・Sprout（面接）・Root",
    folder: "140_Calendar_予定管理",
    iconSrc: "/themes/garden-shell/images/icons_bloom/orb_calendar.png",
  },
];
