"use client";

import { FormEvent, useState } from "react";
import { usePartnerSession } from "../../_components/PartnerGate";
import type { KandenLookup, TossFormInput } from "../_lib/form";
import styles from "./page.module.css";

const initial: TossFormInput = { partnerCode:"",useTossCb:"利用しない",tossCbAmount:"",tossUpItems:[],comment:"",rank:"C",preferredTimes:[],listCategory:"リスト内",pdManagementNumber:"",pd:"",applicantType:"本人",applicantLastName:"",applicantFirstName:"",applicantLastKana:"",applicantFirstKana:"",birthDate:"",addressType:"現住所",postalCode:"",prefecture:"",city:"",town:"",building:"",room:"",contactType:"本人",contactPhone:"",smartphoneCarrier:"その他" };
const selects = { useTossCb:["利用する","利用しない"],rank:["S","A","B","C","D"],listCategory:["リスト内","リスト外"],applicantType:["本人","家族","法人"],addressType:["現住所","転居先","その他"],contactType:["本人","家族","その他"],smartphoneCarrier:["docomo","au","SoftBank","楽天モバイル","その他"] } as const;
const toPd=(managementNumber:string)=>managementNumber.trim()?`PD${managementNumber.trim()}`:"";
const LOOKUP_LABELS:Record<string,string>={listName:"リスト名",customerNumber:"お客様番号",phone:"電話番号",contractNameKanji:"契約名義(漢字)",contractNameKana:"契約名義(カナ)",postalCode:"郵便番号",address1:"住所1",address2:"住所2",leavingDestination:"離脱先",leavingDate:"離脱時期",contractType:"契約種別",contractCapacityLight:"契約容量(従量)",contractCapacityPower:"契約容量(動力)",kandenGasContract:"関電ガス契約",powerContract:"動力契約",demandStartDate:"需要開始日",annualUsageLight:"年間使用量(電灯)",monthlyUsageLight:"月間使用量(電灯)",monthlyUsagePower:"月間使用量(動力)"};
type FieldKey = "tossCbAmount"|"applicantLastName"|"applicantFirstName"|"applicantLastKana"|"applicantFirstKana"|"birthDate"|"postalCode"|"prefecture"|"city"|"town"|"building"|"room"|"contactPhone";
const fieldMeta:Record<FieldKey,{label:string;required?:boolean;type?:string}>={
  tossCbAmount:{label:"キャッシュバック金額",type:"number"}, applicantLastName:{label:"申込者 姓",required:true}, applicantFirstName:{label:"申込者 名",required:true}, applicantLastKana:{label:"申込者 セイ",required:true}, applicantFirstKana:{label:"申込者 メイ",required:true}, birthDate:{label:"生年月日",required:true,type:"date"}, postalCode:{label:"郵便番号",required:true}, prefecture:{label:"都道府県",required:true}, city:{label:"市区町村",required:true}, town:{label:"町域・番地",required:true}, building:{label:"建物名"}, room:{label:"部屋番号"}, contactPhone:{label:"連絡先電話番号",required:true,type:"tel"},
};

export default function TossForm() {
  const session = usePartnerSession();
  const [form,setForm]=useState(initial); const [lookup,setLookup]=useState<KandenLookup|null>(null); const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false); const [completed,setCompleted]=useState<{recordId:string;demo:boolean}|null>(null);
  const set=(key:keyof TossFormInput,value:string|string[])=>setForm(current=>({...current,[key]:value}));
  const multi=(key:"tossUpItems"|"preferredTimes",value:string,checked:boolean)=>set(key,checked?[...form[key],value]:form[key].filter(x=>x!==value));
  async function postalAddress(zip:string){const r=await fetch(`/api/toss/postal?zip=${encodeURIComponent(zip)}`);const b=await r.json();if(!r.ok)throw new Error(b.error);if(!b.found)throw new Error("住所が見つかりませんでした");return b.data as {prefecture:string;city:string;town:string};}
  async function lookupPd(){if(!form.pdManagementNumber.trim()){setMessage("PD管理番号を入力してください。");return;}setBusy(true);setMessage("関電リストを照合しています…");try{const r=await fetch(`/api/toss/kanden-lookup?pd=${encodeURIComponent(form.pdManagementNumber)}`);const b=await r.json();if(!r.ok)throw new Error(b.error);if(!b.found){setLookup(null);setForm(c=>({...c,listCategory:"リスト外"}));setMessage("一致するリストがありません。手入力してください。");return;}const zip=String(b.data.postalCode||"").replace(/-/g,"");let postal:{prefecture:string;city:string;town:string}|null=null;try{if(zip)postal=await postalAddress(zip);}catch{}setLookup(b.data);setForm(c=>({...c,listCategory:"リスト内",postalCode:zip,contactPhone:b.data.phone,prefecture:postal?.prefecture||c.prefecture,city:postal?.city||c.city,town:[postal?.town,b.data.address1,b.data.address2].filter(Boolean).join(" ")}));setMessage("関電リストと一致し、住所を補完しました。");}catch(e){setMessage(e instanceof Error?e.message:"照合に失敗しました");}finally{setBusy(false);}}
  async function lookupPostal(){setBusy(true);try{const data=await postalAddress(form.postalCode);setForm(c=>({...c,...data}));setMessage("住所を補完しました。");}catch(e){setMessage(e instanceof Error?e.message:"住所検索に失敗しました");}finally{setBusy(false);}}
  async function submit(e:FormEvent){e.preventDefault();setBusy(true);setMessage("送信しています…");try{const r=await fetch("/api/toss/submit",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const b=await r.json();if(!r.ok)throw new Error(b.error);setCompleted({recordId:String(b.recordId),demo:b.demo===true});setMessage("");scrollTo({top:0,behavior:"smooth"});}catch(error){setMessage(error instanceof Error?error.message:"送信に失敗しました");}finally{setBusy(false);}}
  function restart(){setForm(initial);setLookup(null);setMessage("");setCompleted(null);scrollTo({top:0,behavior:"smooth"});}
  const onField=(key:FieldKey,value:string)=>set(key,value);
  if(completed)return <section className={styles.complete} aria-labelledby="complete-title"><p>Garden toss portal</p><h2 id="complete-title">送信が完了しました</h2><dl><div><dt>レコード番号</dt><dd>{completed.recordId}</dd></div></dl>{completed.demo&&<strong>デモ送信：実際には登録されていません</strong>}<button type="button" onClick={restart}>続けて入力する</button></section>;
  return <form className={styles.form} onSubmit={submit}>{message&&<div className={styles.notice} role="status">{message}</div>}
    <section><h2>トス情報</h2><div className={styles.grid}><Select label="トスランク" value={form.rank} options={selects.rank} change={v=>set("rank",v)}/><Select label="キャッシュバック有無" value={form.useTossCb} options={selects.useTossCb} change={v=>set("useTossCb",v)}/><Field name="tossCbAmount" form={form} onChange={onField}/><Checks label="トス商材" values={form.tossUpItems} options={["電気","ガス","通信","その他"]} change={(v,c)=>multi("tossUpItems",v,c)}/><Checks label="連絡希望時間帯" values={form.preferredTimes} options={["午前","12〜15時","15〜18時","18時以降"]} change={(v,c)=>multi("preferredTimes",v,c)}/></div></section>
    <section><h2>関電リスト照合</h2><div className={styles.grid}><Select label="関電リスト区分" value={form.listCategory} options={selects.listCategory} change={v=>set("listCategory",v)}/><label>PD管理番号{form.listCategory==="リスト内"&&<em>必須</em>}<span className={styles.inline}><input value={form.pdManagementNumber} required={form.listCategory==="リスト内"} onChange={e=>setForm(c=>({...c,pdManagementNumber:e.target.value,pd:toPd(e.target.value)}))}/><button type="button" disabled={busy} onClick={lookupPd}>照合</button></span></label></div>{lookup&&<dl className={styles.result}>{Object.entries(lookup).map(([k,v])=><div key={k}><dt>{LOOKUP_LABELS[k]??k}</dt><dd>{v||"—"}</dd></div>)}</dl>}</section>
    <section><h2>申込情報</h2><div className={styles.grid}><Select label="申込者区分" value={form.applicantType} options={selects.applicantType} change={v=>set("applicantType",v)}/><Field name="applicantLastName" form={form} onChange={onField}/><Field name="applicantFirstName" form={form} onChange={onField}/><Field name="applicantLastKana" form={form} onChange={onField}/><Field name="applicantFirstKana" form={form} onChange={onField}/><Field name="birthDate" form={form} onChange={onField}/><Select label="住所区分" value={form.addressType} options={selects.addressType} change={v=>set("addressType",v)}/><label>郵便番号<em>必須</em><span className={styles.inline}><input value={form.postalCode} required onChange={e=>set("postalCode",e.target.value)}/><button type="button" disabled={busy} onClick={lookupPostal}>住所検索</button></span></label><Field name="prefecture" form={form} onChange={onField}/><Field name="city" form={form} onChange={onField}/><Field name="town" form={form} onChange={onField}/><Field name="building" form={form} onChange={onField}/><Field name="room" form={form} onChange={onField}/><Field name="contactPhone" form={form} onChange={onField}/><Select label="連絡先区分" value={form.contactType} options={selects.contactType} change={v=>set("contactType",v)}/><Select label="スマホキャリア" value={form.smartphoneCarrier} options={selects.smartphoneCarrier} change={v=>set("smartphoneCarrier",v)}/></div></section>
    <section><h2>パートナー情報</h2><div className={styles.grid}>{session?.kind==="partner"?<div className={styles.readonly}><span>パートナー名</span><strong>{session.partnerName}</strong></div>:<label>パートナーコード<em>必須</em><input inputMode="numeric" value={form.partnerCode||""} required onChange={e=>set("partnerCode",e.target.value.replace(/\D/g,""))}/></label>}<label className={styles.wide}>トス者コメント<textarea rows={4} value={form.comment} onChange={e=>set("comment",e.target.value)}/></label></div></section>
    <button className={styles.submit} disabled={busy}>{busy?"処理中…":"内容を送信する"}</button></form>;
}
function Field({name,form,onChange}:{name:FieldKey;form:TossFormInput;onChange:(key:FieldKey,value:string)=>void}){const meta=fieldMeta[name];return <label>{meta.label}{meta.required&&<em>必須</em>}<input type={meta.type||"text"} value={String(form[name])} required={meta.required} onChange={e=>onChange(name,e.target.value)}/></label>;}
function Select({label,value,options,change}:{label:string;value:string;options:readonly string[];change:(v:string)=>void}){return <label>{label}<select value={value} onChange={e=>change(e.target.value)}>{options.map(x=><option key={x}>{x}</option>)}</select></label>}
function Checks({label,values,options,change}:{label:string;values:string[];options:string[];change:(v:string,c:boolean)=>void}){return <fieldset className={styles.wide}><legend>{label}</legend>{options.map(x=><label key={x}><input type="checkbox" checked={values.includes(x)} onChange={e=>change(x,e.target.checked)}/>{x}</label>)}</fieldset>}
