import {beforeEach,describe,expect,it,vi} from "vitest";
import {syncSubmissionToKintone} from "./submission-kintone.server";
import type {SubmissionRow} from "./submission-types";
const row=(type:"commute_route"|"bank_account"):SubmissionRow=>({id:"1",employee_id:"EMP-1",submission_type:type,payload:type==="commute_route"?{station:"東京駅"}:{bankName:"銀行",bankCode:"1234",branchName:"支店",branchCode:"123",accountNumber:"1234567",holderKana:"ヤマダ"},status:"confirmed",proposed_one_way:500,kintone_status:"pending",kintone_note:null,created_at:""});
const body=(mock:ReturnType<typeof vi.fn>,index:number)=>JSON.parse(String(mock.mock.calls[index][1].body));

describe("temporary Kintone sync",()=>{beforeEach(()=>{vi.unstubAllGlobals();for(const key of ["KINTONE_SUBDOMAIN","KINTONE_COMMUTE_TOKEN","KINTONE_PAYROLL_ACCOUNT_TOKEN","KINTONE_EMPLOYEE_ROSTER_TOKEN"])delete process.env[key]});it("marks missing config as skipped",async()=>{expect(await syncSubmissionToKintone(row("commute_route"),{name:"山田",kot_employee_id:"K1",commute_monthly_cap:20000})).toMatchObject({status:"skipped",note:"Kintone環境変数未設定"})});it("skips without KOTID",async()=>{expect(await syncSubmissionToKintone(row("bank_account"),{name:"役員",kot_employee_id:null,commute_monthly_cap:null})).toMatchObject({status:"skipped",note:expect.stringContaining("KOTID")})})});

describe("configured Kintone sync",()=>{
  beforeEach(()=>{process.env.KINTONE_SUBDOMAIN="garden";process.env.KINTONE_COMMUTE_TOKEN="commute";process.env.KINTONE_PAYROLL_ACCOUNT_TOKEN="bank";process.env.KINTONE_EMPLOYEE_ROSTER_TOKEN="roster"});
  it("checks the roster first, combines tokens for app93, and updates the roster by id",async()=>{const mock=vi.fn().mockResolvedValueOnce(new Response(JSON.stringify({records:[{$id:{value:"newest-id"}}]}),{status:200})).mockResolvedValueOnce(new Response("{}",{status:200})).mockResolvedValueOnce(new Response("{}",{status:200}));vi.stubGlobal("fetch",mock);expect(await syncSubmissionToKintone(row("commute_route"),{name:"山田",kot_employee_id:"K1",commute_monthly_cap:20000})).toMatchObject({status:"synced"});expect(mock).toHaveBeenCalledTimes(3);expect(mock.mock.calls[0][1]).toMatchObject({method:"POST",headers:expect.objectContaining({"X-Cybozu-API-Token":"roster","X-HTTP-Method-Override":"GET"})});expect(body(mock,0).query).toBe('打刻ID = "K1" order by 作成日時 desc limit 1');const record=body(mock,1).record;expect(record).toEqual({ルックアップ:{value:"K1"},文字列__1行_:{value:"山田"},数値:{value:"500"},数値_0:{value:"20000"},文字列__1行__1:{value:"東京駅"}});expect(mock.mock.calls[1][1].headers).toMatchObject({"X-Cybozu-API-Token":"commute,roster"});expect(body(mock,2)).toMatchObject({id:"newest-id",record:{交通費_片道:{value:"500"},交通費上限:{value:"20000"}}});expect(body(mock,2)).not.toHaveProperty("updateKey")});
  it("combines tokens for app92 and uses its actual field codes",async()=>{const mock=vi.fn().mockResolvedValueOnce(new Response(JSON.stringify({records:[{$id:{value:"roster-id"}}]}),{status:200})).mockResolvedValueOnce(new Response("{}",{status:200})).mockResolvedValueOnce(new Response("{}",{status:200}));vi.stubGlobal("fetch",mock);expect(await syncSubmissionToKintone(row("bank_account"),{name:"山田",kot_employee_id:"K1",commute_monthly_cap:null})).toMatchObject({status:"synced"});const record=body(mock,1).record;expect(record).toMatchObject({ルックアップ_0:{value:"K1"},文字列__1行__0:{value:"山田"},文字列__1行_:{value:"1234"},支払先:{value:"山田"},銀行名:{value:"銀行"}});expect(mock.mock.calls[1][1].headers).toMatchObject({"X-Cybozu-API-Token":"bank,roster"});expect(body(mock,2)).toMatchObject({id:"roster-id",record:{銀行名_1:{value:"銀行"},金融機関コード_1:{value:"1234"},支店コード_1:{value:"123"},口座番号_1:{value:"1234567"}}})});
  it("skips all target writes when KOTID is absent from the roster",async()=>{const mock=vi.fn().mockResolvedValueOnce(new Response(JSON.stringify({records:[]}),{status:200}));vi.stubGlobal("fetch",mock);expect(await syncSubmissionToKintone(row("commute_route"),{name:"山田",kot_employee_id:"K1",commute_monthly_cap:20000})).toEqual({status:"skipped",note:"KOTIDが名簿に無いためKintone反映をスキップ"});expect(mock).toHaveBeenCalledTimes(1)});
  it("includes the Kintone response body in the retry note",async()=>{const mock=vi.fn().mockResolvedValueOnce(new Response(JSON.stringify({records:[{$id:{value:"roster-id"}}]}),{status:200})).mockResolvedValueOnce(new Response('{"code":"GAIA_LO04","message":"参照先から値を取得できません"}',{status:400}));vi.stubGlobal("fetch",mock);expect(await syncSubmissionToKintone(row("commute_route"),{name:"山田",kot_employee_id:"K1",commute_monthly_cap:20000})).toEqual({status:"failed",note:expect.stringContaining("GAIA_LO04")})});
});
