import type { SalesMasterRecord } from "./zenkaku-check";
import { ZENKAKU_DROPDOWN_OPTIONS } from "./zenkaku-dropdown-options.generated";
import { mapZenkakuDropdownValue } from "./zenkaku-value-map";

export const DETAIL_FIELD_MAP: Record<keyof Pick<SalesMasterRecord,
  "mobileNumber"|"mobileCarrier"|"mobileDeviceType"|"productCategory1"|"productCategory2"|"salesCommentLine"|"applicationCode"|"applicationPlanName"|"constructionType"|"applicationIsp"|"wirelessUsage"|"wirelessLanCard"|"phonePlanName"|"phoneCallerId"|"phoneCallWaiting"|"phoneNumberRequest"|"phoneNuisanceBlock"|"phoneCallForwarding"|"phoneAdditionalNumber"|"phoneMultipleChannels"|"phoneIncomingMail"|"phoneFaxMail"|"tvApplication"|"terrestrialTvEnvironment"|"quotedPrice"|"existingContractInfo"|"existingContractContinuation"|"existingLineType"|"applicantBirthday"|"thirdPartyLastNameKana"|"thirdPartyFirstNameKana"|"thirdPartyLastName"|"thirdPartyFirstName"|"thirdPartyBirthday"|"thirdPartyAge"|"thirdPartyGender"|"thirdPartyRelationship"|"thirdPartyTalkedAt"|"transferApprovalNumber"|"providerChangeApprovalNumber"|"cafNumber"|"installationPostalCode"|"installationPrefecture"|"installationCity"|"installationTown"|"installationCityKana"|"installationTownKana"|"shippingPostalCode"|"shippingPrefecture"|"shippingCity"|"shippingTown"|"shippingCityKana"|"shippingTownKana">, string> = {
  mobileNumber:"携帯番号_ハイフンなし",mobileCarrier:"携帯キャリア",mobileDeviceType:"携帯端末タイプ",productCategory1:"商材名区分1",productCategory2:"商材名区分2",salesCommentLine:"営コメ_回線",applicationCode:"申込コード",applicationPlanName:"申込プラン名",constructionType:"工事種別",applicationIsp:"申込ISP",wirelessUsage:"無線利用方法",wirelessLanCard:"無線LANカード",phonePlanName:"申込電話プラン名",phoneCallerId:"電話申込OP_発信者番号表示_ND",phoneCallWaiting:"電話申込OP_通話中着信通知_CH",phoneNumberRequest:"電話申込OP_ナンバーリクエスト_NR",phoneNuisanceBlock:"電話申込OP_迷惑電話ブロック",phoneCallForwarding:"電話申込OP_自動転送_VW",phoneAdditionalNumber:"電話申込OP_追加番号",phoneMultipleChannels:"電話申込OP_複数チャネル",phoneIncomingMail:"電話申込OP_着信お知らせメール",phoneFaxMail:"電話申込OP_FAXお知らせメール",tvApplication:"TV申込",terrestrialTvEnvironment:"地デジ環境",quotedPrice:"案内料金",existingContractInfo:"既契約情報",existingContractContinuation:"既契約継続有無",existingLineType:"既契約回線タイプ",applicantBirthday:"申込者名_生年月日",thirdPartyLastNameKana:"第三者確認名_姓カナ",thirdPartyFirstNameKana:"第三者確認名_名カナ",thirdPartyLastName:"第三者確認名_姓",thirdPartyFirstName:"第三者確認名_名",thirdPartyBirthday:"第三者確認名_生年月日",thirdPartyAge:"第三者確認名_年齢",thirdPartyGender:"第三者確認名_性別",thirdPartyRelationship:"第三者確認名_続柄",thirdPartyTalkedAt:"第三者と話した日時",transferApprovalNumber:"転用承諾番号",providerChangeApprovalNumber:"事業者間変更承諾番号",cafNumber:"CAF番号",installationPostalCode:"設置先_郵便番号",installationPrefecture:"設置先_住所_都道府県",installationCity:"設置先_住所_市町村",installationTown:"設置先_住所_町域",installationCityKana:"設置先_住所_市町村_カナ",installationTownKana:"設置先_住所_町域_カナ",shippingPostalCode:"送付先_郵便番号",shippingPrefecture:"送付先_住所_都道府県",shippingCity:"送付先_住所_市町村",shippingTown:"送付先_住所_町域",shippingCityKana:"送付先_住所_市町村_カナ",shippingTownKana:"送付先_住所_町域_カナ"
};

const DROPDOWN_RECORD_KEYS: Record<string, keyof SalesMasterRecord> = {
  TV申込:"tvApplication",商材名区分1:"productCategory1",商材名区分2:"productCategory2",地デジ環境:"terrestrialTvEnvironment",工事種別:"constructionType",携帯キャリア:"mobileCarrier",携帯端末タイプ:"mobileDeviceType",既契約回線タイプ:"existingLineType",既契約継続有無:"existingContractContinuation",無線LANカード:"wirelessLanCard",無線利用方法:"wirelessUsage",申込ISP:"applicationIsp",申込コード:"applicationCode",申込プラン名:"applicationPlanName",申込電話プラン名:"phonePlanName",第三者確認名_性別:"thirdPartyGender",第三者確認名_続柄:"thirdPartyRelationship",電話申込OP_FAXお知らせメール:"phoneFaxMail",電話申込OP_ナンバーリクエスト_NR:"phoneNumberRequest",電話申込OP_発信者番号表示_ND:"phoneCallerId",電話申込OP_着信お知らせメール:"phoneIncomingMail",電話申込OP_自動転送_VW:"phoneCallForwarding",電話申込OP_複数チャネル:"phoneMultipleChannels",電話申込OP_迷惑電話ブロック:"phoneNuisanceBlock",電話申込OP_追加番号:"phoneAdditionalNumber",電話申込OP_通話中着信通知_CH:"phoneCallWaiting",
};
export type DropdownMismatch = { field:string; value:string; message:string };
export function mappedDropdownValues(record:SalesMasterRecord){return Object.fromEntries(Object.entries(DROPDOWN_RECORD_KEYS).map(([field,key])=>[field,mapZenkakuDropdownValue(field,record[key])])) as Record<string,string>}
export function validateZenkakuDropdowns(record:SalesMasterRecord):DropdownMismatch[]{const mapped=mappedDropdownValues(record);return Object.entries(mapped).flatMap(([field,current])=>current&&!((ZENKAKU_DROPDOWN_OPTIONS as Record<string,readonly string[]>)[field]??[]).includes(current)?[{field,value:current,message:`${field}『${current}』は取次側の選択肢にありません。管理者へ連絡してください。`}]:[])}

export const halfWidthAddress = (value: string | null | undefined) => (value ?? "").normalize("NFKC").replace(/[‐‑‒–—―−]/g, "-").replace(/(?<=\d)ー(?=\d)/g, "-");
export function caseYear(record: SalesMasterRecord) { const raw=record.orderDate||record.performanceDate||record.createdAt||""; const match=/^(\d{4})/.exec(raw); return match ? match[1].slice(-2) : "00"; }
const value=(v:unknown)=>({value:v == null ? "" : String(v)});
export function buildKintoneRecords(record: SalesMasterRecord, caseId:string, partnerCode:string, requesterName:string, today:string) {
  const detail:Record<string,{value:string}>={}; for(const [key,field] of Object.entries(DETAIL_FIELD_MAP)) detail[field]=value(record[key as keyof SalesMasterRecord]);
  for(const [field,mapped] of Object.entries(mappedDropdownValues(record))) detail[field]=value(mapped);
  detail["設置先_住所_建物名"]=value(halfWidthAddress(record.installationBuilding)); detail["設置先_住所_部屋番号"]=value(halfWidthAddress(record.installationRoom)); detail["送付先_住所_建物名"]=value(halfWidthAddress(record.shippingBuilding)); detail["送付先_住所_部屋番号"]=value(halfWidthAddress(record.shippingRoom));
  const name=`${record.applicantLastName??""}${record.applicantFirstName??""}`; const kana=`${record.applicantLastNameKana??""}${record.applicantFirstNameKana??""}`;
  const address=[record.installationPrefecture,record.installationCity,record.installationTown,halfWidthAddress(record.installationStreet),halfWidthAddress(record.installationBuilding),halfWidthAddress(record.installationRoom)].filter(Boolean).join("");
  const mapped=mappedDropdownValues(record); const common={案件ID:value(caseId),営業ID:value(record.salesId),獲得手法:value("テレマ"),商材名区分1:value(mapped.商材名区分1),商材名区分2:value(mapped.商材名区分2),案件ステータス:value("前確待ち"),前確依頼日:value(today),受注日:value(record.orderDate),チーム名:value(record.teamName),パートナーコード:value(partnerCode),前確者名:value(requesterName)};
  Object.assign(detail,common,{申込者名_姓名:value(name),申込者名_姓名カナ:value(kana),電話番号_ハイフンなし:value(record.phoneNumber)});
  return {detail,summary:{...common,申込者名:value(name),申込者名_姓名カナ:value(kana),電話番号_ハイフンなし:value(record.phoneNumber),携帯番号_ハイフンなし:value(record.mobileNumber),設置先住所:value(address)}};
}
