-- Preflight (run before applying): root_employees.employee_id must be the text primary key.
-- select column_name, data_type, udt_name
-- from information_schema.columns
-- where table_schema = 'public' and table_name = 'root_employees'
--   and column_name in ('employee_id', 'user_id', 'kot_employee_id')
-- order by column_name;
-- select a.attname as primary_key_column, format_type(a.atttypid, a.atttypmod) as data_type
-- from pg_index i
-- join pg_attribute a on a.attrelid = i.indrelid and a.attnum = any(i.indkey)
-- where i.indrelid = 'public.root_employees'::regclass and i.indisprimary;

alter table public.root_employees
  add column if not exists kot_employee_id text;

create table if not exists public.system_attendance_punches (
  id bigint generated by default as identity primary key,
  employee_id text not null,
  punch_type text not null check (punch_type in ('clock_in', 'clock_out', 'break_start', 'break_end')),
  punched_at timestamptz not null default now(),
  client_punch_id text not null unique
    check (client_punch_id ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'),
  source text not null default 'web',
  user_agent text,
  kot_sync_status text not null default 'unsent'
    check (kot_sync_status in ('unsent', 'sending', 'synced', 'failed', 'resend_wait', 'needs_check')),
  kot_synced_at timestamptz,
  created_at timestamptz not null default now(),
  constraint system_attendance_punches_employee_id_fkey
    foreign key (employee_id) references public.root_employees(employee_id)
);

create index if not exists idx_system_attendance_punches_employee_time
  on public.system_attendance_punches(employee_id, punched_at desc);
create index if not exists idx_system_attendance_punches_sync_time
  on public.system_attendance_punches(kot_sync_status, punched_at desc);

alter table public.system_attendance_punches enable row level security;
-- No browser policies: authenticated Route Handlers verify the user, resolve employee_id,
-- and perform the minimum required operation with the service-role client.

comment on table public.system_attendance_punches is
  'Garden attendance punches awaiting a later KING OF TIME synchronization stage.';
comment on column public.system_attendance_punches.employee_id is
  'Server-resolved root_employees.employee_id (text primary key); client-supplied employee identifiers are never trusted.';
comment on column public.system_attendance_punches.client_punch_id is
  'Browser-generated UUID idempotency key. A retry reuses the same value.';

-- Post-apply verification:
-- select c.column_name, c.data_type, c.udt_name
-- from information_schema.columns c
-- where c.table_schema = 'public' and c.table_name = 'system_attendance_punches'
-- order by c.ordinal_position;
-- select conname, pg_get_constraintdef(oid)
-- from pg_constraint where conrelid = 'public.system_attendance_punches'::regclass;
-- select a.attname as referenced_primary_key, format_type(a.atttypid, a.atttypmod) as data_type
-- from pg_index i
-- join pg_attribute a on a.attrelid = i.indrelid and a.attnum = any(i.indkey)
-- where i.indrelid = 'public.root_employees'::regclass and i.indisprimary;
