create table if not exists public.system_innovera_daily_extension (
  id bigint generated by default as identity primary key,
  employee_id text not null references public.root_employees(employee_id),
  work_date date not null,
  extension text not null,
  started_at timestamptz not null default now(),
  ended_at timestamptz,
  ended_reason text check (ended_reason is null or ended_reason in ('clock_out', 'admin_change')),
  source text not null check (source in ('clock_in', 'admin_change')),
  approved_by_employee_id text references public.root_employees(employee_id),
  punch_id bigint references public.system_attendance_punches(id),
  created_at timestamptz not null default now()
);

create index if not exists idx_system_innovera_daily_extension_employee_date
  on public.system_innovera_daily_extension(employee_id, work_date);

create index if not exists idx_system_innovera_daily_extension_extension_date
  on public.system_innovera_daily_extension(extension, work_date);

create unique index if not exists uq_system_innovera_daily_extension_active_extension
  on public.system_innovera_daily_extension(extension)
  where ended_at is null;

create unique index if not exists uq_system_innovera_daily_extension_active_employee
  on public.system_innovera_daily_extension(employee_id)
  where ended_at is null;

alter table public.system_innovera_daily_extension enable row level security;

drop policy if exists "system_innovera_daily_extension_service_role_all" on public.system_innovera_daily_extension;
create policy "system_innovera_daily_extension_service_role_all"
  on public.system_innovera_daily_extension
  for all
  using (auth.role() = 'service_role')
  with check (auth.role() = 'service_role');
