-- Garden Soil: FileMaker コール履歴の増分取込先（非パーティション初期版）
-- external_call_id は FM「主キー」を文字列化した値。FM「コールID」とは別系列。

create table if not exists public.soil_call_history (
  id bigint generated by default as identity primary key,
  source text not null default 'callcenter-fm-agent',
  external_call_id text not null,

  fm_created_at_raw text,
  fm_created_by text,
  fm_modified_at_raw text,
  fm_modified_by text,
  employee_name text,
  call_date date not null,
  call_time time,
  relationship text,
  result_flag text,
  note text,
  external_call_code text,
  phone_number text,
  employee_id_raw text,
  external_sales_id text,
  sales_count text,
  call_ended_time time,
  list_name text,
  previous_list_name text,

  -- FileMaker が事前計算したトス/獲得/無効/留守/担当不在/見込み/有効、
  -- コール数、s_系、時間集計、DATA0/DATA1等の原値。監査用にのみ保存し、
  -- Garden側の業務集計には使用しない。
  fm_aggregate_raw jsonb not null default '{}'::jsonb,

  imported_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint soil_call_history_external_call_id_key unique (external_call_id)
);

comment on table public.soil_call_history is
  'FileMaker Server 11「コール履歴」の増分取込先。初期版はexternal_call_id単独uniqueを保証するため非パーティション。';
comment on column public.soil_call_history.external_call_id is
  'FileMaker「主キー」(DECIMAL)の文字列化値。コールIDとは別系列で、冪等upsertキー。';
comment on column public.soil_call_history.fm_aggregate_raw is
  'FileMaker事前集計43列中の監査用値。現行FM定義は集計に使用せず、Garden集計はresult_flag等の生データから行う。';

create index if not exists idx_soil_call_history_list_name
  on public.soil_call_history (list_name);
create index if not exists idx_soil_call_history_call_date
  on public.soil_call_history (call_date desc);
create index if not exists idx_soil_call_history_employee_date
  on public.soil_call_history (employee_name, call_date desc);
create index if not exists idx_soil_call_history_phone
  on public.soil_call_history (phone_number);

create or replace function public.soil_call_history_set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists trg_soil_call_history_updated_at on public.soil_call_history;
create trigger trg_soil_call_history_updated_at
  before update on public.soil_call_history
  for each row execute function public.soil_call_history_set_updated_at();

alter table public.soil_call_history enable row level security;
-- anon/authenticated向けpolicyは作成しない。取込APIのservice_roleのみが書き込む。

-- 適用後確認:
-- select count(*) as total, count(distinct external_call_id) as unique_ids from public.soil_call_history;
-- select indexname from pg_indexes where tablename = 'soil_call_history' order by indexname;
-- select relrowsecurity from pg_class where relname = 'soil_call_history';
